ТЗ 9 первая версия
NorthenGirl/java-kanban pull request #4
Opened 2024-03-29 20:18 UTC by NorthenGirl

2024-03-30 16:14 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-03-30 16:14 UTC, ErkinKasymaliev commented on m1-t25-api/.gitignore
> +*.iml
что это за папка m1-t25-api? почему 2 gitignore? 
возможно из-за этого проблемы с тестами в гите

2024-03-30 16:14 UTC, ErkinKasymaliev commented on m1-t25-api/src/Practicum.java
> +class LikesInfo {
почему этот класс здесь?
у тебя 2 src пакета

2024-03-30 16:14 UTC, ErkinKasymaliev commented on src/server/DurationAdapter.java
> +
лишние строки, всегда должна быть 1 пустая строка

2024-03-30 16:14 UTC, ErkinKasymaliev commented on src/server/EpicsHandle.java
> +    private int parsePathId(String path) {
этот метод и 2 ниже у тебя еще повторяются в TasksHandle и SubtaskHandle.
Сделай вот что,:
```
public TaskHandler implements HttpHandler {

    private final TaskManager taskManager;
    private final Gson gson;

    public TaskHandler(TaskManager taskManager) {
        this.taskManager = taskManager;
        gson = HttpTaskServer.getGson();
    }
    
   @Override
   public void handle(HttpExchange httpExchange) throws IOException {
    .....
   }

   protected int parsePathId(String path) {
        try {
            return Integer.parseInt(path);
        } catch (NumberFormatException exception) {
            return -1;
        }
    }

    protected void sendText(HttpExchange exchange, String response) throws IOException {
        byte[] resp = response.getBytes(UTF_8);
        exchange.getResponseHeaders().add("Content-Type", "application/json;charset=utf-8");
        exchange.sendResponseHeaders(200, resp.length);
        exchange.getResponseBody().write(resp);
    }

    protected String readText(HttpExchange exchange) throws IOException {
        return new String(exchange.getRequestBody().readAllBytes(), UTF_8);
    }
}
```
а EpicsHandler и SubtaskHandler, HistoryHandler будет наследовать от него и переиспользовать protected методы

2024-03-30 16:14 UTC, ErkinKasymaliev commented on src/server/HistoryHendler.java
> +public class HistoryHendler implements HttpHandler {
hAndler

2024-03-30 16:14 UTC, ErkinKasymaliev commented on src/server/EpicsHandle.java
> +public class EpicsHandle implements HttpHandler {
HandleR

2024-03-30 16:14 UTC, ErkinKasymaliev commented on src/server/SubtasksHandle.java
> +public class SubtasksHandle implements HttpHandler {
HandleR

2024-03-30 16:14 UTC, ErkinKasymaliev commented on test/server/HistoriServerTest.java
> +public class HistoriServerTest {
HistorY

2024-03-30 16:14 UTC, ErkinKasymaliev commented on test/server/EpicServerTest.java
> +    TaskManager taskManager = Managers.getDefault();
код с 28 по 47 строки у тебя во всех тестах в пакете server повторяется. Создай ServerTest.java пропиши это там и extend его в остальные классы

2024-03-31 10:35 UTC, NorthenGirl commented on m1-t25-api/.gitignore
> +*.iml
Удалила, это была папка проекта из которого мы импортируем  .gson, были трудности его импортом при прохождении тестов на гитхабе, поэтому закинула  ёё полностью, это долгая история )))

2024-03-31 10:35 UTC, NorthenGirl commented on m1-t25-api/src/Practicum.java
> +class LikesInfo {
Это было в продолжение предыдущего комментария, теперь нет.

2024-03-31 10:38 UTC, NorthenGirl commented on src/server/DurationAdapter.java
> +
Удалила, всегда помню  про твою требовательность к чистоте кода, но пока что-нибудь да пропускаю)))

2024-03-31 10:49 UTC, NorthenGirl commented on src/server/HistoryHendler.java
> +public class HistoryHendler implements HttpHandler {
Исправила

2024-03-31 10:54 UTC, NorthenGirl commented on src/server/EpicsHandle.java
> +public class EpicsHandle implements HttpHandler {
Исправила

2024-03-31 10:54 UTC, NorthenGirl commented on src/server/SubtasksHandle.java
> +public class SubtasksHandle implements HttpHandler {
Исправила

2024-03-31 10:55 UTC, NorthenGirl commented on test/server/HistoriServerTest.java
> +public class HistoriServerTest {
Исправила

2024-03-31 12:00 UTC, NorthenGirl commented on src/server/EpicsHandle.java
> +    private int parsePathId(String path) {
Крутая идея, я так и чувствовала, что так не должно быть, но не додумалась до наследования!
Переделала.

2024-03-31 12:00 UTC, NorthenGirl commented on test/server/EpicServerTest.java
> +    TaskManager taskManager = Managers.getDefault();
Переделала

2024-04-01 05:03 UTC, ErkinKasymaliev approved these changes
привет, молодец!
работа принята

2024-04-01 09:12 UTC, merged